# Site settings
title: Blindstore
description: "Open source Private Information Retrieval datastore"
baseurl: "http://blindstore.github.io/blindstore-new-site"
url: "http://blindstore.github.io/blindstore-new-site"
github_username:  blindstore

# Build settings
markdown: kramdown
permalink: pretty

# Sass
sass:
    sass_dir: assets/stylesheets/_scss
    style: :compressed
